# Generated by Django 2.1.1 on 2018-09-23 13:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255, verbose_name='Название')),
                ('description', models.TextField(default='', max_length=5000, verbose_name='Информация')),
                ('schedule_url', models.URLField(default='', max_length=500, verbose_name='Ссылка на график')),
                ('img', models.ImageField(blank=True, default='', upload_to='cinemas/', verbose_name='Фото')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
            ],
            options={
                'verbose_name': 'Кинотеатр',
                'verbose_name_plural': 'Кинотеатры',
                'ordering': ['-add_date'],
            },
        ),
        migrations.CreateModel(
            name='FilmSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, verbose_name='Название')),
                ('time', models.CharField(default='', max_length=255, verbose_name='Время')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Цена')),
                ('film_format', models.CharField(default='', max_length=255, verbose_name='Формат')),
                ('date', models.DateField(default='', verbose_name='Дата')),
                ('cinema', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.Cinema', verbose_name='Кинотеатр')),
            ],
            options={
                'verbose_name': 'График',
                'verbose_name_plural': 'Графики',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.PositiveIntegerField(default=0, verbose_name='ID телеграм аккаунта')),
                ('key', models.CharField(default='', max_length=500, verbose_name='Ключ')),
                ('value', models.TextField(default='', max_length=5000, verbose_name='Значение')),
                ('add_date', models.DateTimeField(auto_now=True, verbose_name='Дата добавления')),
            ],
            options={
                'verbose_name': 'Данные',
                'verbose_name_plural': 'Хранилище',
                'ordering': ['-add_date'],
            },
        ),
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.IntegerField(default=0, verbose_name='ID телеграм аккаунта')),
                ('is_bot', models.BooleanField(default=False, verbose_name='Бот')),
                ('first_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Фамилия')),
                ('username', models.CharField(blank=True, default='', max_length=255, verbose_name='Имя пользователя')),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='telegram_users', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Пользователя телеграм',
                'verbose_name_plural': 'Пользователи телеграма',
                'ordering': ['-add_date'],
            },
        ),
    ]
